import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  stackSidebar: [
		{
			type: 'doc',
			id: 'stack/intro', // document ID
			label: 'Intro', // sidebar label
		}, {
			type: 'category',
			label: 'Layer 1. Ecosystem',
			link: {
				type: "doc",
				id: 'stack/ecosystem/intro',
			},
			collapsible: true,
			items: [
				{
					type: 'category',
					label: 'DLT Networks', // sidebar label
					link: {
						type: "doc",
						id: 'stack/ecosystem/dlts/intro',
					},
					items: [
						'stack/ecosystem/dlts/ecosystems/intro',
						'stack/ecosystem/dlts/ecosystems/bitcoin',
						'stack/ecosystem/dlts/ecosystems/ethereum',
						'stack/ecosystem/dlts/ecosystems/modular',
					]
				}, 
				'stack/ecosystem/exchanges',
				'stack/ecosystem/wallets',
				{
					type: 'category',
					label: 'Smart Contracts',
					link: {
						type: "doc",
						id: 'stack/ecosystem/contracts/intro',
					},
					collapsible: true,
					items: [
						'stack/ecosystem/contracts/storage',
						'stack/ecosystem/contracts/state',
					]
				}, 
			]
		}, {
			type: 'category',
			label: 'Layer 2. Standardization',
			link: {
				type: "doc",
				id: 'stack/standardization/intro',
			},
			collapsible: true,
			items: [
				{
					type: 'category',
					label: 'Tokenization Scope', // sidebar label
					link: {
						type: "doc",
						id: 'stack/standardization/tokenization/intro', // document ID
					},
					collapsible: true,
					items: [
						{
							type: 'category',
							label: 'Tokenization Process',
							items: [
								'stack/standardization/tokenization/process/tokens/index',
								'stack/standardization/tokenization/process/tokenization-demand/index',
								'stack/standardization/tokenization/process/tokenization-supply/index',
								'stack/standardization/tokenization/process/tokenization-monetary-policy/index',
							],
						}, {
							type: 'category',
							label: 'Tokenization Models',
							items: [
								'stack/standardization/tokenization/models/asset/index',
								'stack/standardization/tokenization/models/asset-unbacked/index',
								'stack/standardization/tokenization/models/asset-utility/index',
								'stack/standardization/tokenization/models/asset-security/index',
								'stack/standardization/tokenization/models/asset-stablecoins/index',
								'stack/standardization/tokenization/models/asset-uoa/index',
								'stack/standardization/tokenization/models/asset-nft/index',
							],
						}, {
							type: 'category',
							label: 'Tokenization Utilities',
							items: [
								'stack/standardization/tokenization/utilities/utility/index',
								'stack/standardization/tokenization/utilities/utility-id/index',
								'stack/standardization/tokenization/utilities/utility-investment/index',
								'stack/standardization/tokenization/utilities/utility-currency/index',
							],
						}, 
					],
				}, {
					type: 'category',
					label: 'Tokenization Patterns',
					link: {
						type: "doc",
						id: 'stack/standardization/patterns/intro',
					},
					collapsible: true,
					items: [
						'stack/standardization/patterns/design',
						'stack/standardization/patterns/security',
					]
				}, {
					type: 'category',
					label: 'Fungible Standards',
					link: {
						type: "doc",
						id: 'stack/standardization/fungiblestandards/intro',
					},
					collapsible: true,
					items: [
						{
							type: 'category',
							label: 'ERC-20 Standard',
							link: {
								type: "doc",
								id: 'stack/standardization/fungiblestandards/erc20/intro',
							},
							collapsible: true,
							items: [
								'stack/standardization/fungiblestandards/erc20/state',
								'stack/standardization/fungiblestandards/erc20/supply',
								'stack/standardization/fungiblestandards/erc20/permit',
								'stack/standardization/fungiblestandards/erc20/transfer',
								'stack/standardization/fungiblestandards/erc20/security',
							]
						}, {
							type: "doc",
							id: 'stack/standardization/fungiblestandards/ecosystem',
							label: 'ERC-20 Ecosystems',
						}, {
							type: "doc",
							id: 'stack/standardization/fungiblestandards/other',
							label: 'Alternative Token Standards',
						}, 
					]
				}, 
			]
		}, {
			type: 'category',
			label: 'Layer 3. Principles',
			link: {
				type: "doc",
				id: 'stack/principles/intro',
			},
			collapsible: true,
			items: [
				'stack/principles/value',
				'stack/principles/integrity',
				'stack/principles/friendly',
				'stack/principles/disclosure',
				'stack/principles/metrics',
			]
		}, {
			type: 'category',
			label: 'Layer 4. Immutability',
			link: {
				type: "doc",
				id: 'stack/immutability/intro',
			},
			collapsible: true,
			items: [
				'stack/immutability/immutability',
				'stack/immutability/fungibleimmutability',
			]
		}, {
			type: 'category',
			label: 'Layer 5. Interoperability',
			link: {
				type: "doc",
				id: 'stack/interop/intro',
			},
			collapsible: true,
			items: [
				'stack/interop/agents',
				'stack/interop/communication',
				'stack/interop/patterns',
			]
		}, {
			type: 'category',
			label: 'Layer 6. Specialization',
			link: {
				type: "doc",
				id: 'stack/specialization/intro',
			},
			collapsible: true,
			items: [
				'stack/specialization/memecoin',
				'stack/specialization/fidelization',
				'stack/specialization/reputoken',
				'stack/specialization/utility',
				'stack/specialization/security',
				'stack/specialization/stablecoin',
				'stack/specialization/crommodity',
			]
		}, {
			type: 'category',
			label: 'Layer 7. Application',
			link: {
				type: "doc",
				id: 'stack/application/intro',
			},
			collapsible: true,
			items: [
				{
					type: 'category',
					label: 'Negotiation',
					link: {
						type: "doc",
						id: 'stack/application/negotiation/intro',
					},
					collapsible: true,
					items: [
						'stack/application/negotiation/value',
					]
				}, 
			]
		},   
  ],
  suiteSidebar: [
		{
			type: 'doc',
			id: 'suite/intro', // document ID
			label: 'Suite', // sidebar label
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, 
			'suite/token',
			'suite/interop',
			'suite/dapp',
			'suite/network',
			'suite/ercstandard',
			'suite/exchangelist',
			'suite/relayerlist',
			'suite/walletlist',
		],
  /*valueSidebar: [
		{
			type: 'doc',
			id: 'value/intro', // document ID
			label: 'Getting started', // sidebar label
		}, {
			type: 'html',
      value: '<div class="border border-1 m-3" />',
    }, {
			type: 'doc',
			id: 'value/memecoins', 		// document ID
			label: 'Memecoins', 			// sidebar label
		},{
			type: 'doc',
			id: 'value/reputokens', 	// document ID
			label: 'Reputokens', 			// sidebar label
		},{
			type: 'doc',
			id: 'value/utilities', 		// document ID
			label: 'Utility Tokens', 	// sidebar label
		},{
			type: 'doc',
			id: 'value/securities', 	// document ID
			label: 'Security Tokens', // sidebar label
		},{
			type: 'doc',
			id: 'value/stablecoins', 	// document ID
			label: 'Stablecoins', 		// sidebar label
		},{
			type: 'doc',
			id: 'value/crommodity', 	// document ID
			label: 'Crommodities', 		// sidebar label
		},
  ],*/
	/*valueChainSidebar: [
		{
			type: 'category',
			label: 'Intro',
			link: {
				type: "doc",
				id: 'suite/intro',
			},
			collapsible: true,
			items: [
				'suite/intro',
			],
		},
	],*/
};

export default sidebars;
